import { Router } from 'express';
import { requireAuth } from '../middleware/auth';
import { validate } from '../middleware/validate';
import { upload } from '../middleware/upload';
import { list, get, create, update, addOpening, remove, apply, getApplicants, updateApplicantStatus, convertApplicantToOrder, deleteApplicant, checkUsername, companySchema, updateCompanySchema, openingSchema, applicationSchema, companyApplicationStatusSchema, uploadBanner, uploadAvatar, deleteOpening } from '../controllers/company.controller';
const router = Router();
router.get('/', list);
router.get('/check-username', checkUsername);
router.get('/u/:username', get);
router.post('/', requireAuth, validate(companySchema), create);
router.patch('/:id', requireAuth, validate(updateCompanySchema), update);
router.delete('/:id', requireAuth, remove);
router.post('/:id/openings', requireAuth, validate(openingSchema), addOpening);
router.delete('/openings/:openingId', requireAuth, deleteOpening);
router.post('/openings/:openingId/apply', requireAuth, validate(applicationSchema), apply);
router.get('/openings/:openingId/applicants', requireAuth, getApplicants);
router.patch('/openings/:openingId/applicants/:applicationId/status', requireAuth, validate(companyApplicationStatusSchema), updateApplicantStatus);
router.post('/openings/:openingId/applicants/:applicationId/convert', requireAuth, convertApplicantToOrder);
router.delete('/openings/:openingId/applicants/:applicationId', requireAuth, deleteApplicant);
router.delete('/:companyId/openings/:openingId/applicants/:applicationId', requireAuth, deleteApplicant);
router.post('/:id/banner', requireAuth, upload.single('banner'), uploadBanner);
router.post('/:id/avatar', requireAuth, upload.single('avatar'), uploadAvatar);
export default router;